highlighter: pygments
google_analytics_id: UA-5966233-1
baseurl: ''
permalink: /blog/:year/:month/:day/:title
defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "posts"

# Include files that start with an underscore (e.g. built by phpDocumentor),
# then exclude Jekyll files explicitly later.
include:
  - _*

exclude:
  # Can't exclude _config.yml or _posts.
  - _data
  - _includes
  - _layouts
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - readme.md
