#!/bin/sh

phpdoc -d ../cough/,../cough_generator/,../dal/as/,../as_database/,../as_query/,../schema/,../schema_generator/ -i Test*.class.php,*.inc.php -t ../docs/api/ -ti "CoughPHP API Documentation"
