#!/bin/sh

if test ! $# -eq 2
then
	echo Usage: $0 "cough_checkout_path" "output_name"
	echo For example, from the scripts folder you could run:
	echo "./make_release ../ ../../coughphp-1.1"
	echo which will create "coughphp-1.1.tar.gz"
	exit 1
fi

cp -rp "$1" "$2"
rm -rf "$2/.bzr" "$2/design" "$2/developer_docs" "$2/scripts/make_release" "$2/.bzrignore"
tar -czf "$2.tar.gz" "$2"
