#!/bin/sh

if test ! $# -eq 2
then
	echo Usage: $0 "cough_checkout_path" "output_name"
	echo For example, from the scripts folder you could run:
	echo "./make_release ../ ../../coughphp-1.1"
	echo which will create "coughphp-1.1.tar.gz"
	exit 1
fi

if [ -f "$2" ] || [ -d "$2" ]
then
    echo "Destination already exists. Please remove it first."
	exit 1
fi

cp -Rp "$1" "$2"
rm -rf "$2/.bzr" "$2/.shelf" "$2/.bzrignore" "$2/design" "$2/docs/developer" "$2/scripts/make_release"
find "$2" -name '.DS_Store' -exec rm {} \;
tar -czf "$2.tar.gz" "$2"
