#!/usr/bin/env php
<?php

// CHANGE THIS TO YOUR `simpletest` PATH. (e.g. if it's in the include path, set it to empty string).
define('SIMPLETEST_PATH', 'simpletest/');


/////////////////////////////////
// Don't change anything below //
/////////////////////////////////


// simpletest is not strict compatible, so remove it
$oldErrorReporting = error_reporting();
error_reporting($oldErrorReporting & !E_STRICT);

require_once(SIMPLETEST_PATH . 'autorun.php');
$coughPath = dirname(dirname(__FILE__));
$test = new TestSuite('Running cough tests...');

$test->addTestFile($coughPath . 'cough/tests/TestCoughObject.class.php');
$test->addTestFile($coughPath . 'cough/tests/TestCoughCollection.class.php');
$test->addTestFile($coughPath . 'cough_generator/tests/TestCoughGenerator.class.php');
// $test->addTestFile($coughPath . 'dalal/tests/TestCoughDatabaseFactory.class.php');
// $test->addTestFile($coughPath . 'dalal/tests/TestCoughInstancePool.class.php');

if (TextReporter::inCli())
{
	exit ($test->run(new TextReporter()) ? 0 : 1);
}
$test->run(new HtmlReporter());

?>